### ISSUE TITLE
Won't I need to install a `libc`?

### ISSUE THREAD

**Issue by kiedtl** [Sweets/tldrlfs#1]

**Comment by Sweets** [comment]
Not necessarily, everything in the guide is statically compiled, so it's included in the binaries.

**Comment by kiedtl** [comment]
> Not necessarily, everything in the guide is statically compiled, so it's included in the binaries. You would need one if you plan to use dynamically linked programs or compiling something outside of the system in which everything was built though.

Oh. I see. I tried to statically compile bash, but it gave a lot of linker errors:
```
Using 'endservent' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
Mind helping me fix this?

Also can you give me an outline of how to install glibc anyways? [for other programs necessary?]

Great guide by the way!

**Comment by Sweets** [comment]
Looks like bash might hard-require shared libraries, which sucks (originally the guide used dash, but when I finally got around to adding dash to the README the site went down, so I kind of shoe-horned in bash).

For compiling, it's the usual bullshit with downloading glibc, extracting it, cd'ing (http://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.xz).

Once cd'ed, you'll probably want a build directory. It's going to take a bit to compile, compared to most things (even compared to the kernel, from my experience).

```
mkdir ./build; cd ./build
../configure --prefix=$BUILDDIR/usr                          \
             --disable-werror                       \
             --enable-stack-protector=strong        \
             --with-headers=/usr/include            \
             libc_cv_slibdir=/lib
make
make install
```

You'll also probably want to copy the linker from the current distro to the directory for your tldrlfs build (the location for this can vary, so you'll need to use `find`, you're looking for ld-linux-*.so.*; `find -name 'ld-linux-*.so.*'`, copy it from the directory on the host to $BUILDDIR/lib64. I wouldn't recommend symlinking just for testing, so you'll need to make /lib64 in the $BUILDDIR)

That _should_ install glibc on the system. I will say though that I haven't tested all that yet, so you'll be the guinea pig on this one (and if you run into issues I'll do it on my system and then report back)

**Comment by kiedtl** [comment]
> That should install glibc on the system. I will say though that I haven't tested all that yet, so you'll be the guinea pig on this one (and if you run into issues I'll do it on my system and then report back).

> Just by having the libraries on the system should fix the bash issue.

Misery. It didn't. So far as I know the glibc build process didn't error, but the bash build process still complained.

Then I downloaded dash, compiled and installed it. I then tried to chroot; however dash started to complain about a missing `libc.so.6`. I wasn't sure what to do, so for the moment I copied `/lib/libc.so.6` to `./lib/`. (Correct me if I did this wrong)

Anyway, the chroot is working now :-)

I'll see if it's possible to boot from this thing.

**Comment by Sweets** [comment]
Dash didn't get compiled statically if it complained about libc.so.6. If it works it works I guess lol. I'll redo the shell part of the guide.

Also, don't forget your bootloader. I've yet to add that unfortunately. Working on some other projects at this very moment, but I'll get back to tldrlfs soon.

**Comment by kiedtl** [comment]
> Also, don't forget your bootloader. I've yet to add that unfortunately. Working on some other projects at this very moment, but I'll get back to tldrlfs soon.

I already have reFIND installed.

Anyway lol doesn't this thing need a `/etc/fstab`? and maybe a damned root user too? I tried to boot and got a bunch of cute looking penguins plus an even cuter kernel panic:
```
Kernel panic: vfs blah blah: unable to mount root fs on unknown block (0,0)
```
I'm looking into it right now. Might even have to refer to that eye-glazing abomination, LFS.

**Comment by Sweets** [comment]
`/etc/fstab` isn't required to boot, that's more of a convenience (inits use it to mount devices besides the root filesystem). Also, nope, root user is also not needed. To be strictly literal with it, TLDRLFS just gets the system booting (though apparently not even that lol). Users and such can be added, but it could also be used to just make a dedicated server that boots and starts up a daemon and only does that, without users or anything.

I got the same kernel panic during testing with bcachefs, but I also kind of shrugged it off as I didn't get it with ext4 (fixed it by making an initramfs). During the initial builds (which used ext4) there were no issues. Since I've got some free time, I'll do a build right now.

**Comment by Sweets** [comment]
Just finished a little test build, and I've gotten the same error. Don't really remember what I've done different between now and the first time I wrote the guide, so I'll figure out what it is and comment again. This is just a little update comment.

**Comment by Sweets** [comment]
Figured it out; `root` is a required kernel parameter when not using an initramfs. In my bcachefs build (not that it's relevant here) I couldn't figure out how to get the kernel to use the weird device name structure that bcachefs uses, which is when I then opted to make initramfs.

Add `root=/dev/sdXY` (whatever your root partition is) to your kernel parameters in your bootloader (not sure what that would be for refind, unfortunately). Basically after `rw quiet`.

**Comment by kiedtl** [comment]
> Add root=/dev/sdXY (whatever your root partition is) to your kernel parameters in your bootloader (not sure what that would be for refind, unfortunately). Basically after rw quiet.

Kay, I'll try that out and let you know.

Just thought this you might want to mention this in your guide, but I'm gonna try and use @ dylanaraps kissx package manager as a pkg manager for my lfs installation.

**Comment by kiedtl** [comment]
> Add root=/dev/sdXY (whatever your root partition is) to your kernel parameters in your bootloader (not sure what that would be for refind, unfortunately). Basically after rw quiet.

I'm sure I'm doing something painfully stupid, but when I followed your suggestion I got another kernel panic complaining about a bad RIP value. I think I'll just focus on getting a good chroot environment before trying to boot.

**Comment by Sweets** [comment]
A bad RIP can be pretty vague. Does it say "not syncing: attempted to kill init" anywhere towards the bottom? If this is the case, it means the kernel booted but was either unable to run a process as PID 1 (`/sbin/init`, more specifically, but the kernel may also try `/bin/init`, and a few other locations which are most likely not to contain an init binary) _or_ the process that was previously running as PID 1 was terminated (whether by natural lifetime ending or by an error).

Anything running as the init process must continuously run until the kernel is told to power off the machine, otherwise the kernel will panic.

**Comment by kiedtl** [comment]
> A bad RIP can be pretty vague. Does it say "not syncing: attempted to kill init" anywhere towards the bottom? If this is the case, it means the kernel booted but was either unable to run a process as PID 1 (/sbin/init, more specifically, but the kernel may also try /bin/init, and a few other locations which are most likely not to contain an init binary) or the process that was previously running as PID 1 was terminated (whether by natural lifetime ending or by an error).

Yep, `attempting to kill init `was the error I got.

**Comment by kiedtl** [comment]
@Sweets do you know how to compile `dash` as a static binary? Thanks

**Comment by Sweets** [comment]
```
wget http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.10.tar.gz
cd ./dash-0.5.10
./configure --enable-static --prefix=$BUILDDIR
make
make install
```

Are you on the r/unixporn discord? If so, I can more easily help you there.

**Comment by kiedtl** [comment]
Kay, we can move to discord. What channel?
